id: P3E3A6DFC
initial_creation_type: ocr
source_metadata:
  volumes:
    7d53ddb4c72e4b7887bfa1154f6c7ebb:
      base_file: v013.txt
      image_group_id: I1PD95858
      title: རྣལ་འབྱོར་གྱི་རྒྱུད་དཔལ་གདན་བཞི་པའི་སྒྲུབ་ཐབས།
      total_pages: 2043
      volume_number: 13
