id: D64E04FF1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:38:06+00:00'
last_modified: '2022-05-26T08:05:52.412515+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    444a:
      image_group_id: I1PD95858
      title: རྣལ་འབྱོར་གྱི་རྒྱུད་དཔལ་གདན་བཞི་པའི་སྒྲུབ་ཐབས།
      total_pages: 2043
      order: 13
      base_file: 444a.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
